BEGIN {
	FS = "\t"
	print "// THIS FILE IS AUTOGENERATED, DO NOT EDIT"
}

{
	if (FNR == 1) {
		ncolumns = NF
		for (i = 2; i <= ncolumns; i++) {
			headers[i] = $i
			print "export let " $i " = {};"
		}
	} else {
		for (i = 2; i <= ncolumns; i++) {
			print headers[i] "." $1 " = '" $i "';"
		}
	}
}
